# Neural Network & Deep learning | Project 1

In [0]:
#Import Libraries

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer


In [2]:
 %tensorflow_version 2.x

TensorFlow 2.x selected.


In [3]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


In [0]:
tf.random.set_seed(42)

## Read the dataset in a new python notebook.

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#Reading the file 
data = pd.read_csv('/content/drive/My Drive/bank.csv')

In [7]:
data.shape

(10000, 14)

In [0]:
#The data has 10000 record points and 14 columns.

In [9]:
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

## Drop the columns which are unique for all users like IDs

In [8]:
data["CustomerId"].nunique()

10000

In [9]:
data["RowNumber"].nunique()

10000

In [0]:
#Columns RowNumber and CustomerId are unique to all customers -  dropping those columns. Also, we do  not require Surname column as it
#wont have any relation with the customer leaving the bank, hence we drop that column too.
data = data.drop(["RowNumber","CustomerId", "Surname"], axis=1)

In [27]:
data.shape

(10000, 11)

In [28]:
data.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [34]:
#Check unique values for categorical columns 
data["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [35]:
data["Gender"].unique()

array(['Female', 'Male'], dtype=object)

## Distinguish the feature and target set

In [0]:
#Target column is last column - "Exited" and the rest are feature set
X = data.iloc[:, 0:10].values
y = data.iloc[:, 10].values

In [30]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [31]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [0]:
le = LabelEncoder()#creating label encoder object no. 1 to encode Geography name(index 1 in features)
X[:, 1] = le.fit_transform(X[:, 1])#encoding Geography from string to just 3 no.s 0,1,2 respectively


In [33]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
#Similarly, we label Encode the gender column
X[:, 2] = le.fit_transform(X[:, 2])#encoding Gender from string to just 2 no.s 0,1(male,female) respectively


In [114]:
X[1]

array([608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58], dtype=object)

In [0]:
#Creating dummy variables

ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])],    remainder = 'passthrough')
X = ct.fit_transform(X)


In [120]:
X[1]

array([0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

In [162]:
X.shape

(10000, 12)

## Divide the data set into Train and test sets

In [0]:
#Splitting the feature and target set using train_test_split and standard ratio of 70:30
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30, random_state=0)

## Normalize the train and test data

In [0]:
#Using Standard scaler to normalize the data
sc= StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

## Initialize &amp; build the model

In [0]:
#Importing the Libraries for building ANN model 
from tensorflow.keras.models import Sequential  #For building the Neural Network layer by layer
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout #Dense - To randomly initialize the weights to small numbers close to 0(But not 0)
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras import regularizers
from tensorflow.keras import optimizers
from tensorflow.keras.backend import backend

In [0]:
#We would be building the initial model without any hidden layers.

In [0]:
tf.keras.backend.clear_session()

# Initialize Sequential model
model = Sequential()

In [0]:
#normalize data
model.add(BatchNormalization())

In [0]:
#Output layer
#Sigmoid activation function is used whenever we need Probabilities of 2 categories or less(Similar to Logistic Regression)
#We would switch to Softmax when the dependent variable has more than 2 categories
model.add(Dense(1, activation='sigmoid'))

In [0]:
# Compile the model
#Here we would be using 'adam' optimizer and loss as 'binary_crossentropy' as we have only 2 categories. 
#if more than 2 categories then we use - categorical_crossentropy
model.compile(optimizer= 'adam', loss='binary_crossentropy', metrics=['accuracy'])

In [151]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization (BatchNo multiple                  48        
_________________________________________________________________
dense (Dense)                multiple                  13        
Total params: 61
Trainable params: 37
Non-trainable params: 24
_________________________________________________________________


In [150]:
#Train the model
model.fit(X_train_scaled,y_train,          
          validation_data=(X_test_scaled,y_test),
          epochs=10,
          batch_size=32)

Train on 7000 samples, validate on 3000 samples
Epoch 1/10
7000/7000 [==============================] - 1s 123us/sample - loss: 0.6773 - accuracy: 0.5980 - val_loss: 0.5998 - val_accuracy: 0.6827
Epoch 2/10
7000/7000 [==============================] - 0s 62us/sample - loss: 0.5397 - accuracy: 0.7486 - val_loss: 0.5137 - val_accuracy: 0.7750
Epoch 3/10
7000/7000 [==============================] - 0s 63us/sample - loss: 0.4805 - accuracy: 0.7889 - val_loss: 0.4745 - val_accuracy: 0.7833
Epoch 4/10
7000/7000 [==============================] - 0s 62us/sample - loss: 0.4537 - accuracy: 0.7981 - val_loss: 0.4551 - val_accuracy: 0.7927
Epoch 5/10
7000/7000 [==============================] - 0s 62us/sample - loss: 0.4397 - accuracy: 0.8036 - val_loss: 0.4442 - val_accuracy: 0.8010
Epoch 6/10
7000/7000 [==============================] - 0s 63us/sample - loss: 0.4351 - accuracy: 0.8090 - val_loss: 0.4382 - val_accuracy: 0.8030
Epoch 7/10
7000/7000 [==============================] - 0s 61us/sampl

In [152]:
#Training Accuracy
score = model.evaluate(X_train_scaled, y_train, verbose=0)
print("Train Loss : ", score[0])
print("Train Accuracy : ",score[1])

Train Loss :  0.4292629791668483
Train Accuracy :  0.80985713


In [154]:
#Testing Accuracy
score = model.evaluate(X_test_scaled, y_test, verbose=0)
print("Test Loss : ", score[0])
print("Test Accuracy : ",score[1])

Test Loss :  0.4318587795893351
Test Accuracy :  0.80633336


## Optimize the model 

In [0]:
#We would optimize the model by adding hidden layers to original model and rebuilding the model.

In [0]:
tf.keras.backend.clear_session()

# Initialize Sequential model 
model2 = Sequential()

#normalize data
model2.add(BatchNormalization())

In [0]:
#Adding Hidden Layer 1 
model2.add(Dense(100, activation='relu'))


In [0]:
#Adding Hidden Layer 2
model2.add(Dense(100, activation='relu'))


In [0]:
#Adding Hidden Layer 3
model2.add(Dense(10, activation='relu'))


In [0]:
#Adding Dropout Layer
model2.add(Dropout(0.25))

In [0]:
#Output layer
model2.add(Dense(1, activation='sigmoid'))

In [0]:
# Compile the model
model2.compile(optimizer= 'adam', loss='binary_crossentropy', metrics=['accuracy'])

In [304]:
#Fit the model
#Train the model
model2.fit(X_train_scaled,y_train,          
          validation_data=(X_test_scaled,y_test),
          epochs=30,
          batch_size=32)

Train on 7000 samples, validate on 3000 samples
Epoch 1/30
7000/7000 [==============================] - 1s 167us/sample - loss: 0.4994 - accuracy: 0.7909 - val_loss: 0.4221 - val_accuracy: 0.8270
Epoch 2/30
7000/7000 [==============================] - 1s 93us/sample - loss: 0.4313 - accuracy: 0.8264 - val_loss: 0.3847 - val_accuracy: 0.8487
Epoch 3/30
7000/7000 [==============================] - 1s 91us/sample - loss: 0.4098 - accuracy: 0.8344 - val_loss: 0.3621 - val_accuracy: 0.8503
Epoch 4/30
7000/7000 [==============================] - 1s 91us/sample - loss: 0.3793 - accuracy: 0.8460 - val_loss: 0.3531 - val_accuracy: 0.8513
Epoch 5/30
7000/7000 [==============================] - 1s 86us/sample - loss: 0.3761 - accuracy: 0.8459 - val_loss: 0.3511 - val_accuracy: 0.8607
Epoch 6/30
7000/7000 [==============================] - 1s 86us/sample - loss: 0.3756 - accuracy: 0.8544 - val_loss: 0.3420 - val_accuracy: 0.8617
Epoch 7/30
7000/7000 [==============================] - 1s 94us/sampl

In [281]:
model2.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization (BatchNo multiple                  48        
_________________________________________________________________
dense (Dense)                multiple                  2600      
_________________________________________________________________
dense_1 (Dense)              multiple                  20100     
_________________________________________________________________
dense_2 (Dense)              multiple                  1010      
_________________________________________________________________
dropout (Dropout)            multiple                  0         
_________________________________________________________________
dense_3 (Dense)              multiple                  11        
Total params: 23,769
Trainable params: 23,745
Non-trainable params: 24
___________________________________________________

## Predict the results using 0.5 as a threshold 

In [305]:
# Predicting the Test set results
y_pred = model2.predict(X_test_scaled)

#if y_pred is larger than 0.5 it returns true(1) which means Exited  else false(2) which means - not exited 
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [ True]]


## Print the Accuracy score and confusion matrix

In [306]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix : \n", cm)


Confusion Matrix : 
 [[2287   92]
 [ 342  279]]


In [308]:
#Accuracy calculated from values obtained from Confusion Matrix
accuracy=(2287+279)/3000
print("Test accuracy : ", accuracy)

Test accuracy :  0.8553333333333333


In [309]:
#Testing Accuracy using model.evaluate
score = model2.evaluate(X_test_scaled, y_test, verbose=0)
print("Test Loss : ", score[0])
print("Test Accuracy : ",score[1])

Test Loss :  0.3515751620928446
Test Accuracy :  0.8553333


In [0]:
#Observation - Thus by the addition of Hidden layers we were able to reduce the loss and improve our accuracy score to 85.53%